### ISSUE TITLE
"showTerminal": false

### ISSUE THREAD

**Issue by quantrpeter** [discretegames/f5anything#2] opened 2022-04-18 03:52 UTC
Hi
   "showTerminal": false seems not working, it will jump to focus the terminal
thanks

**Comment by discretegames** [comment] 2022-05-29 22:35
Hmm, I can't reproduce this (in VSCode 1.67.2 on Windows 10).

I'm testing in an empty workspace with a `.vscode/launch.json` like

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "F5 Anything: Custom Command",
            "type": "f5anything",
            "request": "launch",
            "showTerminal": false,
            "command": "echo HELLO"
        }
    ]
}
```

and it seems to work appropriately when both true or false regardless of where the terminal is.

Can you give any more details?

**Comment by discretegames** [comment] 2022-06-04 10:28
Closing as cannot reproduce until more details are given.

**Closed as completed by discretegames** 2022-06-04 10:28 UTC
